version: "3"

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - app

  app:
    container_name: node
    build:
      context: ./node
    ports:
      - "5001:5001"
    depends_on:
      - db
    networks:
      - node-network

  db:
    container_name: node-mysql
    image: mysql:8.1.0
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql:rw
    user: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nodedb
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
